image:
  pullPolicy: Never
httpService:
  ports:
  - port: 9080
    protocol: TCP
    targetPort: http-service
  type: ClusterIP
grpcService:
  ports:
  - port: 50051
    protocol: TCP
    targetPort: grpc-service
  type: ClusterIP
externalhost:
  ports:
  - name: postgre
    port: 5432
    protocol: TCP
    targetPort: postgre-service
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: redis-service
  - name: http
    port: 9080
    protocol: TCP
    targetPort: http-service
  - name: mongo
    port: 27017
    protocol: TCP
    targetPort: mongo-service
  type: ClusterIP
kubernetesClusterDomain: cluster.local
blogServer:
  replicas: 1
  imageVersion: latest
  resourcesLimits:
    cpu: 50m
    memory: 32Mi
cachedRightServer:
  replicas: 1
  imageVersion: latest
  resourcesLimits:
    cpu: 50m
    memory: 32Mi
forumServer:
  replicas: 1
  imageVersion: latest
  resourcesLimits:
    cpu: 50m
    memory: 64Mi
loginServer:
  replicas: 1
  imageVersion: latest
  resourcesLimits:
    cpu: 50m
    memory: 64Mi
markdownServer:
  replicas: 1
  imageVersion: latest
  resourcesLimits:
    cpu: 50m
    memory: 32Mi
proxy:
  replicas: 1
  imageVersion: latest
  resourcesLimits:
    cpu: 50m
    memory: 8Mi
rightServer:
  replicas: 1
  imageVersion: latest
  resourcesLimits:
    cpu: 50m
    memory: 64Mi
saltServer:
  replicas: 1
  imageVersion: latest
  resourcesLimits:
    cpu: 50m
    memory: 32Mi
sessionServer:
  replicas: 1
  imageVersion: latest
  resourcesLimits:
    cpu: 50m
    memory: 32Mi
wikiServer:
  replicas: 1
  imageVersion: latest
  resourcesLimits:
    cpu: 50m
    memory: 32Mi
appServer:
  replicas: 1
  imageVersion: latest
  resourcesLimits:
    cpu: 500m
    memory: 128Mi
