apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: prometheus-server
  namespace: monitoring
  labels:
    monitoring: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - image: prometheus:latest
        imagePullPolicy: Never
        name: puzzletest
        ports:
        - containerPort: 9090
          name: http-service
        volumeMounts:
          - name: prometheus-config
            mountPath: /
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-configmap
