apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-configmap
  namespace: monitoring
  labels:
    monitoring: prometheus
data:
  prometheus.yaml: |-
    global:
      scrape_interval: "1m"
    scrape_configs:
      - job_name: "puzzle"
        static_configs:
          - targets: ["localhost:8889"]
            labels:
              group: "local"
