apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: puzzleblog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: puzzleblog
  template:
    metadata:
      labels:
        app: puzzleblog
    spec:
      containers:
        - name: puzzleblog
          image: puzzleblogserver:latest
          imagePullPolicy: Never
          resources:
            limits:
              memory: "32Mi"
              cpu: "50m"
          ports:
            - containerPort: 50051
              name: grpc-service
          readinessProbe:
            grpc:
              port: 50051
            periodSeconds: 5
            initialDelaySeconds: 1
            failureThreshold: 3
            successThreshold: 1
          envFrom:
            - configMapRef:
                name: puzzleblog-cm
---
apiVersion: v1
kind: Service
metadata:
  name: puzzleblog-service
spec:
  selector:
    app: puzzleblog
  ports:
  - protocol: TCP
    port: 50051
    targetPort: grpc-service
