apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: puzzletest
  namespace: default
  labels:
    app: puzzletest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: puzzletest
  template:
    metadata:
      labels:
        app: puzzletest
    spec:
      containers:
        - name: puzzletest
          image: puzzletest:latest
          imagePullPolicy: Never
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
              name: http-service
          readinessProbe:
            httpGet:
              path: /favicon.ico
              port: 8080
            periodSeconds: 5
            initialDelaySeconds: 1
            failureThreshold: 3
            successThreshold: 1
          envFrom:
            - configMapRef:
                name: puzzletest-cm
---
apiVersion: v1
kind: Service
metadata:
  name: puzzletest-service
spec:
  selector:
    app: puzzletest
  ports:
  - protocol: TCP
    port: 8080
    targetPort: http-service
