apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: puzzleright
spec:
  replicas: 1
  selector:
    matchLabels:
      app: puzzleright
  template:
    metadata:
      labels:
        app: puzzleright
    spec:
      containers:
        - name: puzzleright
          image: puzzlerightserver:latest
          resources:
            limits:
              memory: "64Mi"
              cpu: "50m"
          ports:
            - containerPort: 50051
              name: grpc-service
          readinessProbe:
            grpc:
              port: 50051
            periodSeconds: 5
            initialDelaySeconds: 1
            failureThreshold: 3
            successThreshold: 1
          envFrom:
            - configMapRef:
                name: puzzleright-cm
---
apiVersion: v1
kind: Service
metadata:
  name: puzzleright-service
spec:
  selector:
    app: puzzleright
  ports:
  - protocol: TCP
    port: 50051
    targetPort: grpc-service
