apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: puzzleforum
spec:
  replicas: 1
  selector:
    matchLabels:
      app: puzzleforum
  template:
    metadata:
      labels:
        app: puzzleforum
    spec:
      containers:
        - name: puzzleforum
          image: puzzleforumserver:latest
          imagePullPolicy: Never
          resources:
            limits:
              memory: "64Mi"
              cpu: "50m"
          ports:
            - containerPort: 50051
              name: grpc-service
          readinessProbe:
            grpc:
              port: 50051
            periodSeconds: 5
            initialDelaySeconds: 1
            failureThreshold: 3
            successThreshold: 1
          envFrom:
            - configMapRef:
                name: puzzleforum-cm
---
apiVersion: v1
kind: Service
metadata:
  name: puzzleforum-service
spec:
  selector:
    app: puzzleforum
  ports:
  - protocol: TCP
    port: 50051
    targetPort: grpc-service
