apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: puzzlecachedright
spec:
  replicas: 1
  selector:
    matchLabels:
      app: puzzlecachedright
  template:
    metadata:
      labels:
        app: puzzlecachedright
    spec:
      containers:
        - name: puzzlecachedright
          image: puzzlecachedrightserver:latest
          imagePullPolicy: Never
          resources:
            limits:
              memory: "32Mi"
              cpu: "50m"
          ports:
            - containerPort: 50051
              name: grpc-service
          readinessProbe:
            grpc:
              port: 50051
            periodSeconds: 5
            initialDelaySeconds: 1
            failureThreshold: 3
            successThreshold: 1
          envFrom:
            - configMapRef:
                name: puzzlecachedright-cm
---
apiVersion: v1
kind: Service
metadata:
  name: puzzlecachedright-service
spec:
  selector:
    app: puzzlecachedright
  ports:
  - protocol: TCP
    port: 50051
    targetPort: grpc-service
