apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: {{ include "puzzle.fullname" . }}-app
  labels:
    {{- include "puzzle.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.appServer.replicas }}
  selector:
    matchLabels:
      app: puzzleapp
  template:
    metadata:
      labels:
        app: puzzleapp
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: puzzletest-cm
        image: puzzletest:{{ .Values.appServer.replicas }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: puzzletest
        ports:
        - containerPort: 9080
          name: http-service
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /favicon.ico
            port: 9080
          initialDelaySeconds: 1
          periodSeconds: 5
          successThreshold: 1
        resources:
          limits:
            {{- .Values.appServer.resourcesLimits | toYaml | nindent 12 -}}
