apiVersion: v1
kind: Service
metadata:
  name: {{ include "puzzle.fullname" . }}-blog-service
  labels:
  {{- include "puzzle.labels" . | nindent 4 }}
spec:
  type: {{ .Values.blogService.type }}
  selector:
    app: puzzleblog
  {{- include "puzzle.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.blogService.ports | toYaml | nindent 2 -}}