apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: {{ include "puzzle.fullname" . }}-cachedright
  labels:
  {{- include "puzzle.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: puzzlecachedright
  template:
    metadata:
      labels:
        app: puzzlecachedright
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: puzzlecachedright-cm
        image: puzzlecachedrightserver:latest
        imagePullPolicy: Never
        name: puzzlecachedright
        ports:
        - containerPort: 50051
          name: grpc-service
        readinessProbe:
          failureThreshold: 3
          grpc:
            port: 50051
          initialDelaySeconds: 1
          periodSeconds: 5
          successThreshold: 1
        resources:
          limits:
            cpu: 50m
            memory: 32Mi