apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: {{ include "puzzle.fullname" . }}-cachedright
  labels:
    {{- include "puzzle.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.cachedRightServer.replicas }}
  selector:
    matchLabels:
      app: puzzlecachedright
  template:
    metadata:
      labels:
        app: puzzlecachedright
        {{- include "puzzle.labels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: RIGHT_SERVICE_ADDR
          value: "{{ include "puzzle.fullname" . }}-right-service:50051"
        - name: UNUSED_DATA_TIMEOUT
          value: "600"
        - name: REDIS_SERVER_ADDR
          value: "{{ .Values.externalService.redisAddr }}"
        - name: REDIS_SERVER_DB
          value: "1"
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: "$(HOST_IP):4317"
        image: puzzlecachedrightserver:{{ .Values.cachedRightServer.imageVersion }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: puzzlecachedright
        ports:
        - containerPort: 50051
          name: grpc-service
        readinessProbe:
          failureThreshold: 3
          grpc:
            port: 50051
          initialDelaySeconds: 1
          periodSeconds: 5
          successThreshold: 1
        resources:
          limits:
            {{- .Values.cachedRightServer.resourcesLimits | toYaml | nindent 12 -}}
