apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: {{ include "puzzle.fullname" . }}-forum
  labels:
    {{- include "puzzle.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.forumServer.replicas }}
  selector:
    matchLabels:
      app: puzzleforum
  template:
    metadata:
      labels:
        app: puzzleforum
        {{- include "puzzle.labels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: DB_SERVER_TYPE
          value: "postgres"
        - name: DB_SERVER_ADDR
          value: "host={{ include "puzzle.fullname" . }}-externalhost user=postgres dbname=forumdb port=5432 sslmode=disable"
        image: puzzleforumserver:{{ .Values.forumServer.imageVersion }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: puzzleforum
        ports:
        - containerPort: 50051
          name: grpc-service
        readinessProbe:
          failureThreshold: 3
          grpc:
            port: 50051
          initialDelaySeconds: 1
          periodSeconds: 5
          successThreshold: 1
        resources:
          limits:
            {{- .Values.forumServer.resourcesLimits | toYaml | nindent 12 -}}
