apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: {{ include "puzzle.fullname" . }}-login
  labels:
    {{- include "puzzle.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.loginServer.replicas }}
  selector:
    matchLabels:
      app: puzzlelogin
  template:
    metadata:
      labels:
        app: puzzlelogin
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: puzzlelogin-cm
        image: puzzleloginserver:{{ .Values.loginServer.imageVersion }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: puzzlelogin
        ports:
        - containerPort: 50051
          name: grpc-service
        readinessProbe:
          failureThreshold: 3
          grpc:
            port: 50051
          initialDelaySeconds: 1
          periodSeconds: 5
          successThreshold: 1
        resources:
          limits:
            {{- .Values.loginServer.resourcesLimits | toYaml | nindent 12 -}}
