apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: {{ include "puzzle.fullname" . }}-login
  labels:
    {{- include "puzzle.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.loginServer.replicas }}
  selector:
    matchLabels:
      app: puzzlelogin
  template:
    metadata:
      labels:
        app: puzzlelogin
        {{- include "puzzle.labels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: DB_SERVER_TYPE
          value: "postgres"
        - name: DB_SERVER_ADDR
          value: "{{ .Values.externalService.postgresqlAddr }} dbname=logindb"
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: "$(HOST_IP):4317"
        image: puzzleloginserver:{{ .Values.loginServer.imageVersion }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: puzzlelogin
        ports:
        - containerPort: 50051
          name: grpc-service
        readinessProbe:
          failureThreshold: 3
          grpc:
            port: 50051
          initialDelaySeconds: 1
          periodSeconds: 5
          successThreshold: 1
        resources:
          limits:
            {{- .Values.loginServer.resourcesLimits | toYaml | nindent 12 -}}
