apiVersion: v1
kind: Service
metadata:
  name: {{ include "puzzle.fullname" . }}-markdown-service
  labels:
  {{- include "puzzle.labels" . | nindent 4 }}
spec:
  type: {{ .Values.markdownService.type }}
  selector:
    app: puzzlemarkdown
  {{- include "puzzle.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.markdownService.ports | toYaml | nindent 2 -}}