apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: {{ include "puzzle.fullname" . }}-passstrength
  labels:
    {{- include "puzzle.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.passstrengthserver.replicas }}
  selector:
    matchLabels:
      app: puzzlepassstrength
  template:
    metadata:
      labels:
        app: puzzlepassstrength
        {{- include "puzzle.labels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: DEFAULT_PASSWORD
          value: "{{ .Values.passstrengthserver.defaultPassword }}"
        - name: AVAILABLE_LOCALES
          value: "fr-FR, en-US"
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: "http://$(HOST_IP):4317"
        image: puzzlepassstrengthserver:{{ .Values.passstrengthserver.imageVersion }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: puzzlepassstrength
        ports:
        - containerPort: 5432
          name: postgre-service
        - containerPort: 6379
          name: redis-service
        - containerPort: 9080
          name: http-service
        - containerPort: 27017
          name: mongo-service
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 9080
          initialDelaySeconds: 1
          periodSeconds: 5
          successThreshold: 1
        resources:
          limits:
            {{- .Values.passstrengthserver.resourcesLimits | toYaml | nindent 12 -}}
