apiVersion: v1
kind: Service
metadata:
  name: {{ include "puzzle.fullname" . }}-profile-service
  labels:
  {{- include "puzzle.labels" . | nindent 4 }}
spec:
  type: {{ .Values.profileService.type }}
  selector:
    app: puzzleprofile
  {{- include "puzzle.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.profileService.ports | toYaml | nindent 2 -}}