apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: {{ include "puzzle.fullname" . }}-proxy
  labels:
    {{- include "puzzle.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.proxy.replicas }}
  selector:
    matchLabels:
      app: puzzleproxy
  template:
    metadata:
      labels:
        app: puzzleproxy
    spec:
      containers:
      - env:
        - name: SERVICE_PORT
          value: "9080"
        - name: SERVICE_PORTS
          value: "5432,6379,27017"
        - name: FORWARD_HOSTS
          value: "{{ .Values.proxy.postgresqlAddr }},{{ .Values.proxy.redisAddr }},{{ .Values.proxy.mongoAddr }}"
        image: puzzleproxy:{{ .Values.proxy.imageVersion }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: puzzleproxy
        ports:
        - containerPort: 5432
          name: postgre-service
        - containerPort: 6379
          name: redis-service
        - containerPort: 9080
          name: http-service
        - containerPort: 27017
          name: mongo-service
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 9080
          initialDelaySeconds: 1
          periodSeconds: 5
          successThreshold: 1
        resources:
          limits:
            {{- .Values.proxy.resourcesLimits | toYaml | nindent 12 -}}
