apiVersion: v1
kind: Service
metadata:
  name: {{ include "puzzle.fullname" . }}-right-service
  labels:
  {{- include "puzzle.labels" . | nindent 4 }}
spec:
  type: {{ .Values.rightService.type }}
  selector:
    app: puzzleright
  {{- include "puzzle.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.rightService.ports | toYaml | nindent 2 -}}