apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: {{ include "puzzle.fullname" . }}-right
  labels:
    {{- include "puzzle.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.rightServer.replicas }}
  selector:
    matchLabels:
      app: puzzleright
  template:
    metadata:
      labels:
        app: puzzleright
        {{- include "puzzle.labels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: DB_SERVER_TYPE
          value: "postgres"
        - name: DB_SERVER_ADDR
          value: "{{ .Values.externalService.postgresqlAddr }} dbname=rightdb"
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: "http://$(HOST_IP):4317"
        image: puzzlerightserver:{{ .Values.rightServer.imageVersion }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: puzzleright
        ports:
        - containerPort: 50051
          name: grpc-service
        readinessProbe:
          failureThreshold: 3
          grpc:
            port: 50051
          initialDelaySeconds: 1
          periodSeconds: 5
          successThreshold: 1
        resources:
          limits:
            {{- .Values.rightServer.resourcesLimits | toYaml | nindent 12 -}}
