apiVersion: v1
kind: Service
metadata:
  name: {{ include "puzzle.fullname" . }}-salt-service
  labels:
  {{- include "puzzle.labels" . | nindent 4 }}
spec:
  type: {{ .Values.saltService.type }}
  selector:
    app: puzzlesalt
  {{- include "puzzle.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.saltService.ports | toYaml | nindent 2 -}}