apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: {{ include "puzzle.fullname" . }}-session
  labels:
    {{- include "puzzle.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.sessionServer.replicas }}
  selector:
    matchLabels:
      app: puzzlesession
  template:
    metadata:
      labels:
        app: puzzlesession
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: puzzlesession-cm
        image: puzzlesessionserver:{{ .Values.sessionServer.imageVersion }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: puzzlesession
        ports:
        - containerPort: 50051
          name: grpc-service
        readinessProbe:
          failureThreshold: 3
          grpc:
            port: 50051
          initialDelaySeconds: 1
          periodSeconds: 5
          successThreshold: 1
        resources:
          limits:
            {{- .Values.sessionServer.resourcesLimits | toYaml | nindent 12 -}}
