apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: {{ include "puzzle.fullname" . }}-settings
  labels:
  {{- include "puzzle.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: puzzlesettings
  template:
    metadata:
      labels:
        app: puzzlesettings
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: puzzlesettings-cm
        image: puzzlesettingsserver:latest
        imagePullPolicy: Never
        name: puzzlesettings
        ports:
        - containerPort: 50051
          name: grpc-service
        readinessProbe:
          failureThreshold: 3
          grpc:
            port: 50051
          initialDelaySeconds: 1
          periodSeconds: 5
          successThreshold: 1
        resources:
          limits:
            cpu: 50m
            memory: 32Mi