apiVersion: v1
kind: Service
metadata:
  name: {{ include "puzzle.fullname" . }}-settings-service
  labels:
  {{- include "puzzle.labels" . | nindent 4 }}
spec:
  type: {{ .Values.settingsService.type }}
  selector:
    app: puzzlesettings
  {{- include "puzzle.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.settingsService.ports | toYaml | nindent 2 -}}