apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: {{ include "puzzle.fullname" . }}-settings
  labels:
    {{- include "puzzle.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.settingsServer.replicas }}
  selector:
    matchLabels:
      app: puzzlesettings
  template:
    metadata:
      labels:
        app: puzzlesettings
        {{- include "puzzle.labels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: MONGODB_SERVER_ADDR
          value: "{{ .Values.externalService.mongoAddr }}"
        - name: MONGODB_SERVER_DB
          value: "settingsDB"
        image: puzzlesettingsserver:{{ .Values.settingsServer.imageVersion }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: puzzlesettings
        ports:
        - containerPort: 50051
          name: grpc-service
        readinessProbe:
          failureThreshold: 3
          grpc:
            port: 50051
          initialDelaySeconds: 1
          periodSeconds: 5
          successThreshold: 1
        resources:
          limits:
            {{- .Values.settingsServer.resourcesLimits | toYaml | nindent 12 -}}
