apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: {{ include "puzzle.fullname" . }}-template
  labels:
    {{- include "puzzle.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.templateServer.replicas }}
  selector:
    matchLabels:
      app: puzzletemplate
  template:
    metadata:
      labels:
        app: puzzletemplate
        {{- include "puzzle.labels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: DATE_FORMAT
          value: "{{ .Values.appServer.internalDateFormat }}"
        - name: EXEC_ENV
          value: {{ .Values.telemetry.envName }}
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: "http://$(HOST_IP):4317"
        image: "{{ .Values.templateServer.imageName }}:{{ .Values.templateServer.imageVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: puzzletemplate
        ports:
        - containerPort: 50051
          name: grpc-service
        readinessProbe:
          failureThreshold: 3
          grpc:
            port: 50051
          initialDelaySeconds: 1
          periodSeconds: 5
          successThreshold: 1
        resources:
          limits:
            {{- .Values.templateServer.resourcesLimits | toYaml | nindent 12 -}}
