apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: {{ include "puzzle.fullname" . }}-wiki
  labels:
    {{- include "puzzle.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.wikiServer.replicas }}
  selector:
    matchLabels:
      app: puzzlewiki
  template:
    metadata:
      labels:
        app: puzzlewiki
        {{- include "puzzle.labels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: MONGODB_SERVER_ADDR
          value: "{{ .Values.externalService.mongoAddr }}"
        - name: MONGODB_SERVER_DB
          value: "wikisDB"
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: "http://$(HOST_IP):4317"
        image: puzzlewikiserver:{{ .Values.wikiServer.imageVersion }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: puzzlewiki
        ports:
        - containerPort: 50051
          name: grpc-service
        readinessProbe:
          failureThreshold: 3
          grpc:
            port: 50051
          initialDelaySeconds: 1
          periodSeconds: 5
          successThreshold: 1
        resources:
          limits:
            {{- .Values.wikiServer.resourcesLimits | toYaml | nindent 12 -}}
